FROM python:3.11-slim

WORKDIR /app

# Copiar e instalar dependencias de Python
COPY Requirements.Frontend.txt .
# Línea corregida con la URL oficial de PyTorch para CPU:
RUN pip install --no-cache-dir -r Requirements.Frontend.txt

# Copiar el código de la app gráfica
COPY Frontend/ .
COPY .env /app/.env

# Exponer el puerto por defecto de Streamlit
EXPOSE 8501

# Comando para ejecutar Streamlit
CMD ["streamlit", "run", "Aplicacion_Grafica.py", "--server.port=8501", "--server.address=0.0.0.0"]
