FROM python:3.11-slim

WORKDIR /app

# Copiar requirements primero (mejor cache)
COPY Requirements.Frontend.txt .

# Actualizar pip (recomendado)
RUN pip install --upgrade pip

# Instalar dependencias
RUN pip install --no-cache-dir -r Requirements.Frontend.txt

# Copiar código frontend
COPY . .

# Exponer puerto Streamlit
EXPOSE 8501

# Ejecutar app
CMD ["streamlit", "run", "Aplicacion_Grafica.py", "--server.port=8501", "--server.address=0.0.0.0"]