#version: '3.8'

services:

  backend:
    build:
      context: ../Backend
      dockerfile: ../Archivos_Docker/DockerFile.Backend

    container_name: challenge_alura_backend

    ports:
      - "8000:8000"

    env_file:
      - ../Backend/.env


    volumes:
      # Cache del modelo de HuggingFace
      - hf_cache:/root/.cache/huggingface

      # Persistencia de la base vectorial ChromaDB
      - chroma_data:/app/chroma_db

    restart: unless-stopped

  frontend:
    build:
      context: ../Frontend
      dockerfile: ../Archivos_Docker/DockerFile.Frontend

    container_name: challenge_alura_frontend

    ports:
      - "8501:8501"

    env_file:
      - ../Frontend/.env

    depends_on:
      - backend
      

    restart: unless-stopped

volumes:
  # Cache del modelo de embeddings
  hf_cache:

  # Base vectorial persistente
  chroma_data: